import type { Metadata } from "next";
import { Inter } from "next/font/google";

import RQProvider from "@/app/components/RQProvider";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark max-w-6xl mx-auto`}>
        <div className="bg-green-900 text-white mb-5 flex px-5 py-2 items-center rounded-b-lg">
          <div className="text-2xl font-bold flex-grow">Show Voter</div>
        </div>
        <RQProvider>{children}</RQProvider>
      </body>
    </html>
  );
}
